-- COMPLETE IMPORT SCRIPT FOR DEMO ACCOUNT
-- Run this in Supabase SQL Editor

-- Step 1: Clean existing demo data
DELETE FROM commission_rules WHERE user_email = 'Demo@AgentCommissionTracker.com';
DELETE FROM carrier_mga_relationships WHERE user_email = 'Demo@AgentCommissionTracker.com';
DELETE FROM mgas WHERE user_email = 'Demo@AgentCommissionTracker.com';
DELETE FROM carriers WHERE user_email = 'Demo@AgentCommissionTracker.com';

-- Step 2: Insert all carriers
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Citizens', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'AAA', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Progressive', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Tower Hill', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Heritage', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Universal', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Florida Peninsula', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Federated National', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'St. Johns', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Southern Oak', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'American Integrity', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'People's Trust', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'First Community', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Centauri', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Kin', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Slide', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'TypTap', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Homeowners Choice', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'United Property & Casualty', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Safe Harbor', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Elements', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Cypress', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Prepared', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Velocity', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Orchid', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Edison', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Olympus', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Weston', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Monarch', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Family Security', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Lighthouse', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Anchor', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'ASI/Progressive', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Foremost', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'American Strategic (ASI)', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Bristol West', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Safeco', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Travelers', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Allstate', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'State Farm', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Farmers', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Liberty Mutual', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'MetLife', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Hartford', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Chubb', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Nationwide', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Mercury', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'USAA', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Auto-Owners', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Erie', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'American Family', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Kemper', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Esurance', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), '21st Century', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'National General', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'The General', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Infinity', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Hagerty', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Grundy', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Dairyland', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Wright Flood', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Neptune', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO carriers (carrier_id, carrier_name, naic_code, producer_code, status, user_email) VALUES (gen_random_uuid(), 'Beyond Flood', NULL, NULL, 'Active', 'Demo@AgentCommissionTracker.com');

-- Step 3: Insert all MGAs
INSERT INTO mgas (mga_id, mga_name, status, user_email) VALUES (gen_random_uuid(), 'Direct Appointment', 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO mgas (mga_id, mga_name, status, user_email) VALUES (gen_random_uuid(), 'SureTec', 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO mgas (mga_id, mga_name, status, user_email) VALUES (gen_random_uuid(), 'Advantage Partners', 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO mgas (mga_id, mga_name, status, user_email) VALUES (gen_random_uuid(), 'Florida Peninsula MGA', 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO mgas (mga_id, mga_name, status, user_email) VALUES (gen_random_uuid(), 'Simon Agency', 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO mgas (mga_id, mga_name, status, user_email) VALUES (gen_random_uuid(), 'Iroquois MGA', 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO mgas (mga_id, mga_name, status, user_email) VALUES (gen_random_uuid(), 'Strategic Insurance Partners', 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO mgas (mga_id, mga_name, status, user_email) VALUES (gen_random_uuid(), 'Southern Risk MGA', 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO mgas (mga_id, mga_name, status, user_email) VALUES (gen_random_uuid(), 'Coastal MGA', 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO mgas (mga_id, mga_name, status, user_email) VALUES (gen_random_uuid(), 'Premier MGA', 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO mgas (mga_id, mga_name, status, user_email) VALUES (gen_random_uuid(), 'Elite MGA Services', 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO mgas (mga_id, mga_name, status, user_email) VALUES (gen_random_uuid(), 'Professional Risk MGA', 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO mgas (mga_id, mga_name, status, user_email) VALUES (gen_random_uuid(), 'Atlantic MGA', 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO mgas (mga_id, mga_name, status, user_email) VALUES (gen_random_uuid(), 'Gulf Coast MGA', 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO mgas (mga_id, mga_name, status, user_email) VALUES (gen_random_uuid(), 'Sunshine State MGA', 'Active', 'Demo@AgentCommissionTracker.com');
INSERT INTO mgas (mga_id, mga_name, status, user_email) VALUES (gen_random_uuid(), 'First Choice MGA', 'Active', 'Demo@AgentCommissionTracker.com');

-- Step 4: Insert commission rules
-- Note: These use subqueries to find the carrier and MGA IDs
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'Citizens' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', NULL, 10.0, 10.0, 'Citizens standard rate', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'AAA' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', 'Auto,Package', 12.0, 12.0, 'AAA Auto and Package products', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'AAA' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', 'Home,Membership', 15.0, 15.0, 'AAA Home and Membership products', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'AAA' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', 'Umbrella', 10.0, 10.0, 'AAA Umbrella products', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'Progressive' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', 'Auto', 12.0, 10.0, 'Progressive auto insurance', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'Progressive' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', 'Home', 15.0, 12.0, 'Progressive home insurance', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'Progressive' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', 'Renters', 15.0, 15.0, 'Progressive renters insurance', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'Progressive' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', 'Boat', 10.0, 10.0, 'Progressive boat insurance', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'Tower Hill' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', NULL, 18.0, 15.0, 'Tower Hill standard rate', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'Heritage' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', NULL, 11.0, 11.0, 'Heritage standard rate', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'Universal' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', NULL, 12.0, 8.0, 'Universal standard rate', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'Florida Peninsula' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', NULL, 10.0, 10.0, 'Florida Peninsula standard rate', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'Federated National' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', NULL, 8.0, 8.0, 'Federated National standard rate', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'St. Johns' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', NULL, 10.0, 10.0, 'St. Johns standard rate', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'Southern Oak' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', NULL, 10.0, 8.5, 'Southern Oak standard rate', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'American Integrity' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', NULL, 12.0, 8.0, 'American Integrity standard rate', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'State Farm' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'SureTec' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', NULL, 14.0, 12.0, 'State Farm through SureTec', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'Mercury' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Advantage Partners' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', NULL, 8.0, 6.0, 'Mercury through Advantage Partners', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'Safeco' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', 'Auto', 12.0, 10.0, 'Safeco Auto insurance', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'Safeco' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', 'Home', 15.0, 15.0, 'Safeco Home insurance', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'Travelers' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', NULL, 12.0, 12.0, 'Travelers standard rate', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'Travelers' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', 'Umbrella', 10.0, 10.0, 'Travelers Umbrella product', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'Chubb' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', 'Auto,BOP,Umbrella', 15.0, 15.0, 'Chubb Auto/BOP/Umbrella products', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'Chubb' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', 'Cyber', 18.0, 15.0, 'Chubb Cyber Liability', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'National General' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', NULL, 12.0, 12.0, 'National General standard rate', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'Wright Flood' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', NULL, 15.0, 15.0, 'Wright Flood standard rate', 'Demo@AgentCommissionTracker.com', false, true);
INSERT INTO commission_rules (carrier_id, mga_id, state, policy_type, new_rate, renewal_rate, rule_description, user_email, is_default, is_active) VALUES ((SELECT carrier_id FROM carriers WHERE carrier_name = 'Neptune' AND user_email = 'Demo@AgentCommissionTracker.com'), (SELECT mga_id FROM mgas WHERE mga_name = 'Direct Appointment' AND user_email = 'Demo@AgentCommissionTracker.com'), 'FL', NULL, 12.0, 12.0, 'Neptune flood insurance', 'Demo@AgentCommissionTracker.com', false, true);

-- Step 5: Verify import
SELECT 'Import complete!' as status;
SELECT 'Carriers: ' || COUNT(*) FROM carriers WHERE user_email = 'Demo@AgentCommissionTracker.com'
UNION ALL SELECT 'MGAs: ' || COUNT(*) FROM mgas WHERE user_email = 'Demo@AgentCommissionTracker.com'
UNION ALL SELECT 'Commission Rules: ' || COUNT(*) FROM commission_rules WHERE user_email = 'Demo@AgentCommissionTracker.com';
